CREATE TABLE EMPLOYEE(
     EMPLOYEE_ID  INT(3) PRIMARY KEY,
     FIRST_NAME VARCHAR(20),
	 LAST_NAME VARCHAR(20),
     EMAIL VARCHAR(20),
	 PHONE_NUMBER VARCHAR(15),
     HIRE_DATE VARCHAR(20),
     JOB_ID VARCHAR(20),
	 SALARY INT(6),
	 MANAGER_ID INT(5),
	 DEPARTMENT_ID INT(5)	 
 );
 
 
 
 INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) 
 VALUES (?, ?, ?, ?, ?,?, ?, ?, ?, ?);